# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Macbook Air'
  demands:
    - Agent.Name -equals ubuntu-server

variables:
  dockerRegistryServiceConnection: 'Dockerhub-baohq3'  # tên service connection trong Azure DevOps
  imageRepository: 'baohq3/frontend'
  dockerfilePath: 'frontend/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: build
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      tags: |
        $(tag)

  - task: Docker@2
    displayName: 'Push Docker image'
    inputs:
      command: push
      repository: $(imageRepository)
      tags: |
        $(tag)

  - script: echo "✅ Image $(imageRepository):$(tag) pushed to Docker Hub"
    displayName: 'Confirm Push'



#- task: Docker@2
#  inputs:
#    containerRegistry: 'Dockerhub-baohq3'
#    repository: 'baohq3/frontend'
#    command: 'build'
#    Dockerfile: '**/Dockerfile'


